// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the predicted prompt text, or silence when no suggestion is suitable.
 */
export type ThreadSuggestNextPromptResponse = {
/**
 * Composer-ready prompt text after server-side suppression and filtering.
 */
suggestion: string | null, };
