// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests a best-effort predicted next prompt for one loaded thread.
 *
 * This is an internal interactive-client helper. The request does not advance
 * the thread or persist a new item; it asks the server to sample from the
 * thread's current prompt-visible history.
 */
export type ThreadSuggestNextPromptParams = {
/**
 * Thread whose current completed history should be used for prediction.
 */
threadId: string,
/**
 * Optional client token used to cancel an older in-flight suggestion request.
 *
 * Reusing a token cancels the older request before this request samples.
 */
cancellationToken?: string | null,
/**
 * When true, cancel the request identified by `cancellation_token` without sampling.
 *
 * This requires `cancellation_token`.
 */
cancel?: boolean | null, };
